version: 2
jobs:
  build:
    working_directory: ~/timekit-io/booking-js
    docker:
    - image: circleci/node:lts-browsers
    steps:
    - checkout
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-{{ .Revision }}
        # Default branch if not
        - v1-dep-master-
    - run:
        name: Install dependencies
        command: |
            node -v
            yarn -v
            yarn install --pure-lockfile
            yarn add node-sass
            yarn rebuild node-sass
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ .Revision }}
        paths:
        - ~/.cache/yarn
        - ./node_modules
    # Run frontend tests
    - run:
        name: Test unit suite and build prod
        command: |
            yarn run test